[alias]
lint = [
     "clippy",
     "--",
     "-D",
     "clippy::pedantic",
     "-D",
     "clippy::cargo",
     "-A",
     "clippy::if_not_else",
     "-A",
     "clippy::similar_names",
     "-A",
     "clippy::too_many_lines"
]
