[alias]
lint = [
     "clippy",
     "--",
     "-D",
     "clippy::pedantic",
     "-D",
     "clippy::cargo",
     "-A",
     "clippy::if_not_else",
     "-A",
     "clippy::similar_names",
     "-A",
     "clippy::multiple_crate_versions",
     "-A",
     "clippy::doc_markdown"
]
